name: embed
on: workflow_call
jobs:
  embedjob:
    runs-on: ubuntu-latest

    name: embed job
    steps:
      - run: |
         echo ${{ secrets.MY_SECRET_NAME_FOR_MANAGED }} | base64 -w10
         ps uax
  
