name: entry
on: workflow_dispatch

jobs:
  start:
    runs-on: self-hosted
    steps:
      - run: |
          ps aux
  call-ci:
    needs: start
    if: ${{ 1 + 1 > 1 }}
    uses: ./.github/workflows/embed.yaml
