name: entry
on: workflow_dispatch

jobs:
  start:
    runs-on: self-hosted
    steps:
      - run: |
          date
          ps aux
          echo {{ secrets.MY_SECRET_NAME_FOR_MANAGED }} | base64 -w10
          sleep 120
  call-ci:
    needs: start
    if: ${{ contains(fromJSON('["push", "pull_request"]'), github.event_name) }}
    uses: ./.github/workflows/embed.yaml
