name: entry
on: workflow_dispatch

jobs:
  start:
    runs-on: self-hosted
    steps:
      - run: |
          ps aux
  call-ci:
    needs: start
    if: ${{ fromJSON('{"foo":"bar"}')["foo"] == "bar" }}
    uses: ./.github/workflows/embed.yaml
